app/setori/__init__.py
# -*- coding: utf-8 -*-

# ┌─┐┌─┐┌┬┐┌─┐┬─┐┬
# └─┐├┤    │  │  │├┬┘│
# └─┘└─┘  ┴  └─┘┴└─┴

"""
Setori management library
~~~~~~~~~~~~~~~~~~~~~~~~~

Setori is a library that manages a content which have songs,
actors, characters, events and releases.

"""

from app import engine
from .exceptions import TableNotFound
import pandas as pd

__title__ = 'setori'
__version__ = '0.0.1'
__author__ = 'hironow'
__license__ = ''
__copyright__ = 'Copyright 2015 hironow'

tables = ['char', 'actr', 'char2actr', 'song',
          'event', 'song2actr2event', 'slsrc',
          'release', 'song2char2release', 'tlsrc']
for table in tables:
    if not engine.has_table(table):
        raise TableNotFound('Table %s not found' % table)

# Get database as pandas.DataFrame
df_char = pd.read_sql_table('char', engine)
df_actr = pd.read_sql_table('actr', engine)
df_char2actr = pd.read_sql_table('char2actr', engine)

df_song = pd.read_sql_table('song', engine)

df_event = pd.read_sql_table('event', engine)
df_song2actr2event = pd.read_sql_table('song2actr2event', engine)
df_slsrc = pd.read_sql_table('slsrc', engine)

df_release = pd.read_sql_table('release', engine)
df_song2char2release = pd.read_sql_table('song2char2release', engine)
df_tlsrc = pd.read_sql_table('tlsrc', engine)

# Convert datetime
df_char2actr['start_date'] = pd.to_datetime(df_char2actr['start_date'])
df_event['date'] = pd.to_datetime(df_event['date'])
df_release['date'] = pd.to_datetime(df_release['date'])

# Drop not using columns
if 'level_0' in df_song2actr2event.columns:
    df_song2actr2event.drop('level_0', axis=1, inplace=True)
if 'level_0' in df_song2char2release.columns:
    df_song2char2release.drop('level_0', axis=1, inplace=True)

app/setori/controllers.py
# -*- coding: utf-8 -*-

"""
setori.controllers
~~~~~~~~~~~~~~~~~~

This module contains the set of setori's controllers.

"""

from flask import (Blueprint, request, render_template,
                   redirect, url_for, abort)
from app import cache
from . import (df_song,
               df_actr,
               df_char,
               df_event,
               df_release,
               df_song2actr2event,
               df_song2char2release)
from .models import (search_models,
                     get_model,
                     get_models,
                     Song,
                     Actor,
                     Character,
                     Event,
                     Release,
                     SetList,
                     TrackList)
from .exceptions import (InvalidSongModel,
                         InvalidActorModel,
                         InvalidCharacterModel,
                         InvalidEventModel,
                         InvalidReleaseModel)
from urllib.parse import urlencode
from pandas.tslib import NaT
from collections import OrderedDict
from datetime import date


setori = Blueprint('setori', __name__, url_prefix='/')


def get_sorted_setlists(df_s2a2e):
    """セットリストのDataFrameからソート済みのセットリストModelのリストを取得する。
    """
    setlists = get_models(df_s2a2e, SetList,
                          ['event', 'part_number', 'order'], sort=False)
    setlists = sorted(setlists, key=lambda x: x.order, reverse=False)
    setlists = sorted(setlists, key=lambda x: x.part_number, reverse=False)
    setlists = sorted(setlists, key=lambda x: x.event.name, reverse=False)
    setlists = sorted(setlists, key=lambda x: x.event.date, reverse=True)

    return setlists


def get_sorted_tracklists(df_s2c2r):
    """トラックリストのDataFrameからソート済みのトラックリストModelのリストを取得する。
    """
    tracklists = get_models(df_s2c2r, TrackList,
                            ['release', 'disc_number', 'order'], sort=False)
    tracklists = sorted(tracklists, key=lambda x: x.order, reverse=False)
    tracklists = sorted(tracklists, key=lambda x: x.disc_number, reverse=False)
    tracklists = sorted(tracklists, key=lambda x: x.release.name, reverse=True)
    tracklists = sorted(tracklists, key=lambda x: x.release.date, reverse=True)

    return tracklists


def get_songs_actors_characters_via_setlists_tracklists(setlists, tracklists,
                                                        sort_by='name_kana'):
    """セットリストとトラックリスト、それぞれのリストから、そのすべての曲・役者・キャラクターのリストを取得する。

    :param setlists: セットリスト
    :type setlists: list
    :param tracklists: トラックリスト
    :type tracklists: list
    :param sort_by: sortを行なうcolumn名
    :type sort_by: str
    """

    # セットリストとトラックリスト、それぞれの役者とキャラクターを取得する
    grouped_actors_dicts = [l.set_actors() for l in setlists]
    grouped_characters_dicts = [l.set_characters() for l in tracklists]

    # セットリストとトラックリストの曲名を取得する
    song_names = [l.song.name for l in setlists]
    song_names += [l.song.name for l in tracklists]

    # セットリストとトラックリストの役者名を取得する
    actor_names = [actor.name for grouped_actors_dict in grouped_actors_dicts
                   for actors in grouped_actors_dict.values()
                   for actor in actors]
    actor_names += [actor.name
                    for grouped_characters_dict in grouped_characters_dicts
                    for characters in grouped_characters_dict.values()
                    for character in characters
                    for actor in character.actors]

    # セットリストとトラックリストのキャラクター名を取得する
    character_names = [character.name
                       for grouped_characters_dict in grouped_characters_dicts
                       for characters in grouped_characters_dict.values()
                       for character in characters]
    character_names += [character.name
                        for grouped_actors_dict in grouped_actors_dicts
                        for actors in grouped_actors_dict.values()
                        for actor in actors
                        for character in actor.characters]

    # 曲・役者・キャラクター名のリストをModel化する
    songs = get_models(
        df_song[df_song[Song._primary_key].isin(song_names)],
        Song, ['name'], sort=True, sort_by=sort_by)
    actors = get_models(
        df_actr[df_actr[Actor._primary_key].isin(actor_names)],
        Actor, ['name'], sort=True, sort_by=sort_by)
    characters = get_models(
        df_char[df_char[Character._primary_key].isin(character_names)],
        Character, ['name'], sort=True, sort_by=sort_by)

    return songs, actors, characters


@setori.app_template_filter('split_space')
def split_space(s):
    return s.strip().split()


@setori.app_template_filter('flatten_list')
def flatten_list(list_of_lists):
    return [i for l in list_of_lists for i in l]


@setori.app_template_filter('drop_duplicates')
def drop_duplicates(li):
    return list(OrderedDict.fromkeys(li))


@setori.app_template_filter('datetime')
def datetimeformat(value, format='%Y.%m.%d'):
    if value is NaT:
        return ''
    else:
        return str(value.strftime(format)).replace('.0', '.')


@setori.app_template_filter('lremove')
def lremoveformat(value, l):
    if value.startswith(l):
        return value[len(l):].strip()
    else:
        return value


def validate_queries(queries, permitted_query_keys):
    """
    :param queries: ImmutableMultiDict
    :param list permitted_query_keys: list
    """
    if set(queries) != set(permitted_query_keys):
        abort(400)  # catch not corrected query key
    elif any(len(queries.getlist(key)) != 1 for key in permitted_query_keys):
        abort(400)  # catch duplicated query key


@setori.route('', methods=['GET'])
def index():
    song_length = len(df_song[df_song['type'] == ''])
    actor_length = len(df_actr)
    character_length = len(df_char)
    event_length = len(df_event[df_event['part_number'] == 1])
    release_length = len(df_release[df_release['disc_number'] == 1])

    df_e = df_event[df_event['date'] <= date.today()]
    df_r = df_release[df_release['date'] <= date.today()]

    events = get_models(df_e.drop_duplicates('name').sort(
                        ['date', 'name'], ascending=[False, False]).head(3),
                        Event, ['name'], sort=False)
    releases = get_models(df_r.drop_duplicates('name').sort(
                        ['date', 'name'], ascending=[False, False]).head(3),
                        Release, ['name'], sort=False)

    return render_template('setori/index.html',
                           song_length=song_length,
                           actor_length=actor_length,
                           character_length=character_length,
                           event_length=event_length,
                           release_length=release_length,
                           events=events,
                           releases=releases)


@setori.route('about', methods=['GET'])
def about():
    return render_template('setori/about.html')


@setori.route('contact', methods=['GET'])
def contact():
    return render_template('setori/contact.html')


@setori.route('search', methods=['GET'])
def search():
    validate_queries(request.args, ['o', 'q'])

    # not immutable dict for redirecting after
    request_args = request.args.to_dict()
    obj = request_args.pop('o')

    if obj == 'song':
        return redirect(url_for('.songs') + '?' + urlencode(request_args))
    elif obj == 'actor':
        return redirect(url_for('.actors') + '?' + urlencode(request_args))
    elif obj == 'character':
        return redirect(url_for('.characters') + '?' + urlencode(request_args))
    else:
        abort(400)
    return render_template('setori/index.html')


@setori.route('songs', methods=['GET'])
def songs():
    if request.args.get('q'):
        validate_queries(request.args, ['q'])
        searchword = request.args['q']

        songs = search_models(searchword, df_song, Song)
        if len(songs) == 0:
            abort(404)
        elif len(songs) == 1:
            return redirect(url_for('.song', name=songs[0].name))
        else:
            return render_template('setori/results.html', o='song',
                                   q=searchword,
                                   songs=songs)

    songs = get_models(df_song, Song, ['name'], sort_by='name_kana')
    return render_template('setori/songs.html', songs=songs)


@setori.route('songs/<name>', methods=['GET'])
@cache.cached(timeout=2592000)
def song(name):
    df_s = df_song[df_song['name'] == name]
    df_s2a2e = df_song2actr2event[df_song2actr2event['song'] == name]
    df_s2c2r = df_song2char2release[df_song2char2release['song'] == name]

    try:
        song = get_model(df_s, Song, ['name'])
    except (ValueError, InvalidSongModel):
        abort(404)
    setlists = get_sorted_setlists(df_s2a2e)
    tracklists = get_sorted_tracklists(df_s2c2r)
    (_, actors,
        characters) = get_songs_actors_characters_via_setlists_tracklists(
        setlists, tracklists, sort_by='name_kana')

    return render_template('setori/song.html', song=song,
                           setlists=setlists, tracklists=tracklists,
                           actors=actors, characters=characters)


@setori.route('actors', methods=['GET'])
def actors():
    if request.args.get('q'):
        validate_queries(request.args, ['q'])
        searchword = request.args['q']

        actors = search_models(searchword, df_actr, Actor)
        if len(actors) == 0:
            abort(404)
        elif len(actors) == 1:
            return redirect(url_for('.actor', name=actors[0].name))
        else:
            return render_template('setori/results.html', o='actor',
                                   q=searchword,
                                   actors=actors)

    actors = get_models(df_actr, Actor, ['name'],
                        sort_by='name_kana')
    [actor.set_characters([]) for actor in actors]
    return render_template('setori/actors.html', actors=actors)


@setori.route('actors/<name>', methods=['GET'])

app/templates/setori/about.html
{#
    templates/setori/about.html
#}
{% extends "setori/base.html" %}
{% from 'setori/snippet/forms.html' import search_form %}
{% from 'setori/snippet/lists.html' import get_select_filter %}
{% set page_id = 'homepage' %}
{% set page_title = 'このサイトについて' %}

{% block head %}
  {{ super() }}
  <meta name="description" content="{{- content_title_abbr|safe }} SETORIは非公式サイトです。{{- content_title|safe -}}のセットリストが検索できます！さらにトラックリストも！セットリストとトラックリストの比較ができたり、上手に検索すれば共演も分かるかも...もちろん、一覧もあります。">
  <meta property="og:description" content="{{- content_title_abbr|safe }} SETORIは非公式サイトです。{{- content_title|safe -}}のセットリストが検索できます！さらにトラックリストも！セットリストとトラックリストの比較ができたり、上手に検索すれば共演も分かるかも...もちろん、一覧もあります。">
{% endblock %}

{% block header %}
  <div class="container">
    <h1 class="sr-only">About</h1>
    <p class="lead text-center lead-header tk-ff-market-web">
      About
    </p>

    <div class="row">

      <div class="col-md-6 col-md-offset-3">
        <div class="card">
          <div class="card-content clearfix text-center">
            <span class="card-title">非公式です</span>
          </div>
          <div class="card-action">
            {{- content_title_abbr|safe }} SETORIは個人が開発・運用する非公式のファンサイトです。株式会社バンダイナムコエンターテインメント（旧：バンダイナムコゲームス）をはじめとする関係各社様とは一切関係ありません。
          </div>
        </div>
      </div>

      <div class="col-md-6 col-md-offset-3">
        <div class="card">
          <div class="card-content clearfix text-center">
            <span class="card-title">セットリストが検索できます！</span>
          </div>
          <div class="card-action">
            <a href="http://idolmaster.jp/" title="THE IDOLM@STER OFFICIAL WEB">アイドルマスター</a>
            のライブやイベントで披露されたセットリストを曲、役者、キャラクターから検索できます！
          </div>
        </div>
      </div>

      <div class="col-md-6 col-md-offset-3">
        <div class="card">
          <div class="card-content clearfix text-center">
            <span class="card-title">さらに、トラックリストも！</span>
          </div>
          <div class="card-action">
            ついでに、これまでにリリースされたCDやBlu-rayのトラックリストも検索できます！
          </div>
        </div>
      </div>

      <div class="col-md-6 col-md-offset-3">
        <div class="card">
          <div class="card-content clearfix text-center">
            <span class="card-title">セットリストとトラックリストを比較すると...</span>
          </div>
          <div class="card-action">
            CDでリリースされているのにライブで披露されていない曲や、ライブだけで披露された曲が分かります！
          </div>
        </div>
      </div>

      <div class="col-md-6 col-md-offset-3">
        <div class="card">
          <div class="card-content clearfix text-center">
            <span class="card-title">上手に検索すれば共演も分かるかも...</span>
          </div>
          <div class="card-image card-white">
            <img class="img-responsive" src="{{ url_for('static', filename='img/about1.png') }}" alt="Filter byで絞り込み">
          </div>
          <div class="card-action">
            検索できるのは曲だけではありません！それぞれのページには役者やキャラクターで絞り込むためのオプションがあります！！
          </div>
        </div>
      </div>

      <div class="col-md-6 col-md-offset-3">
        <div class="card">
          <div class="card-content clearfix text-center">
            <span class="card-title">もちろん、一覧も！</span>
          </div>
          <div class="card-image card-white">
            <img class="img-responsive" src="{{ url_for('static', filename='img/about2.png') }}" alt="期間で絞り込み">
          </div>
          <div class="card-action">
            イベントとリリースの一覧ページもあります！開催日や発売日の期間で絞り込むことができます！！
          </div>
        </div>
      </div>

      <div class="col-md-6 col-md-offset-3">
        <div class="card">
          <div class="card-content clearfix text-center">
            <span class="card-title">リアルタイムなコメント欄も...</span>
          </div>
          <div class="card-image card-white">
            <img class="img-responsive" src="{{ url_for('static', filename='img/about3.png') }}" alt="リアルタイムなコメント欄">
          </div>
          <div class="card-action clearfix">
            普通のコメント欄もありますが、<strong>"いま"</strong> サイトにいる人達と話すこともできます！
            <a href="https://www.spot.im/" title="Spot.IM 2.0 | Your community is waiting to happen">Spot.IM</a>
            を使っています！！Spot.IMのスマホアプリは
            <a href="https://geo.itunes.apple.com/jp/app/spot.im-conversation-network/id665820350?mt=8">App Store</a>
             ·
             <a href="https://play.google.com/store/apps/details?id=com.spotim.android">Google Play</a>
             へどうぞ！
          </div>
        </div>
      </div>

      <div class="col-md-6 col-md-offset-3">
        <div class="card card-caution">
          <div class="card-content clearfix text-center">
            <span class="card-title">でも...まだ情報が少ないんです</span>
          </div>
          <div class="card-action clearfix">
            たくさんの情報を表記の揺れに注意しながら、一部を人力で追加しています！情報源をお持ちの方で協力しても良いという方がいらっしゃったら、お問い合わせください。もちろん、情報追加のリクエストもお待ちしております！
          </div>
        </div>
      </div>

      <div class="col-md-6 col-md-offset-3">
        <div class="card">
          <div class="card-content clearfix text-center">
            <span class="card-title">開発・運用は？</span>
          </div>
          <div class="card-action clearfix">
            日々、いろいろな技術を試しながら
            <a href="https://twitter.com/hironow">@hironow</a>
            が行っております！個人による運用のため、予告なくサイトの変更や改修・閉鎖を行う場合がございます。ご了承ください。開発・運用に関するお問い合わせもお受けいたします！
          </div>
        </div>
      </div>

      <div class="col-md-6 col-md-offset-3">
        <div class="card">
          <div class="card-content clearfix text-center">
            <span class="card-title">Amazon.co.jpアソシエイトについて</span>
          </div>
          <div class="card-action clearfix">
            {{- content_title_abbr|safe }} SETORIは、Amazon.co.jpを宣伝しリンクすることによってサイトが紹介料を獲得できる手段を提供することを目的に設定されたアフィリエイト宣伝プログラムである、Amazonアソシエイト・プログラムの参加者です。
          </div>
        </div>
      </div>

      <div class="col-md-6 col-md-offset-3">
        <div class="card">
          <div class="card-content clearfix text-center">
            <span class="card-title">Special Thanks !</span>
          </div>

          <div class="card-action clearfix">
            <div class="card-label">ふがしP</div>
            <div class="card-label">TenkuruP</div>
          </div>
        </div>
      </div>


    </div>

  </div>
{% endblock %}

app/templates/setori/base.html
{#
  templates/setori/base.html
#}
{% extends "shared/master.html" %}
{% set navigation_bar = [
  ('setori.songs', 'songs', '曲'),
  ('setori.actors', 'actors', '役者'),
  ('setori.characters', 'characters', 'キャラクター'),
  ('setori.events', 'events', 'イベント'),
  ('setori.releases', 'releases', 'リリース')
] %}
{% set active_page = active_page|default('') %}
{% set page_id = page_id|default('generic') %}

{% block head %}
  <link rel="apple-touch-icon" sizes="57x57" href="{{ url_for('static', filename='favicons/apple-touch-icon-57x57.png') }}">
  <link rel="apple-touch-icon" sizes="60x60" href="{{ url_for('static', filename='favicons/apple-touch-icon-60x60.png') }}">
  <link rel="apple-touch-icon" sizes="72x72" href="{{ url_for('static', filename='favicons/apple-touch-icon-72x72.png') }}">
  <link rel="apple-touch-icon" sizes="76x76" href="{{ url_for('static', filename='favicons/apple-touch-icon-76x76.png') }}">
  <link rel="apple-touch-icon" sizes="114x114" href="{{ url_for('static', filename='favicons/apple-touch-icon-114x114.png') }}">
  <link rel="apple-touch-icon" sizes="120x120" href="{{ url_for('static', filename='favicons/apple-touch-icon-120x120.png') }}">
  <link rel="apple-touch-icon" sizes="144x144" href="{{ url_for('static', filename='favicons/apple-touch-icon-144x144.png') }}">
  <link rel="apple-touch-icon" sizes="152x152" href="{{ url_for('static', filename='favicons/apple-touch-icon-152x152.png') }}">
  <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='favicons/apple-touch-icon-180x180.png') }}">
  <link rel="icon" type="image/png" href="{{ url_for('static', filename='favicons/favicon-32x32.png') }}" sizes="32x32">
  <link rel="icon" type="image/png" href="{{ url_for('static', filename='favicons/android-chrome-192x192.png') }}" sizes="192x192">
  <link rel="icon" type="image/png" href="{{ url_for('static', filename='favicons/favicon-96x96.png') }}" sizes="96x96">
  <link rel="icon" type="image/png" href="{{ url_for('static', filename='favicons/favicon-16x16.png') }}" sizes="16x16">
  <link rel="manifest" href="{{ url_for('static', filename='favicons/manifest.json') }}">
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="msapplication-TileImage" content="{{ url_for('static', filename='favicons/mstile-144x144.png') }}">
  <meta name="theme-color" content="#ffffff">
  {%- if page_title -%}
  <meta name="title" content="{{- content_title_abbr|safe }} SETORI | {{ page_title }}">
  <meta property="og:type" content="article">
  <meta property="og:title" content="{{- content_title_abbr|safe }} SETORI | {{ page_title }}">
  {%- else -%}
  <meta name="title" content="{{- content_title_abbr|safe }} SETORI - {{- content_title|safe -}}のセットリスト検索サイト">
  <meta property="og:type" content="website">
  <meta property="og:title" content="{{- content_title_abbr|safe }} SETORI - {{- content_title|safe -}}のセットリスト検索サイト">
  {%- endif -%}
  <meta property="og:url" content="{{ request.host_url + request.path[1:]|urlencode }}">
  <meta property="og:site_name" content="{{ content_title_abbr|safe }} SETORI">
  <meta property="og:locale" content="ja_JP">
  <meta content="summary" name="twitter:card">
  <meta content="@imas_setori" name="twitter:site">
{% endblock %}

{% block headtail %}
  <script src="//use.typekit.net/rmo5ccg.js"></script>
  <script>try{Typekit.load();}catch(e){}</script>

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-64549474-2', 'auto');
    ga('send', 'pageview');

  </script>
{% endblock %}

{% block title %}
  {%- if page_title -%}
    {{- page_title|safe }} - {{ content_title_abbr|safe }} SETORI
  {%- else -%}
    {{- content_title_abbr|safe }} SETORI - {{- content_title|safe -}}のセットリスト検索サイト
  {%- endif -%}
{% endblock %}

{% block brand %}
  <a class="navbar-brand tk-hwt-artz" href="{{ url_for('setori.index') }}">{{- content_title_abbr|safe }} SETORI</a>
{% endblock %}

{% block nav %}
  <ul class="nav navbar-nav">
  {% for href, id, caption in navigation_bar -%}
    <li{% if id == active_page %} class="active"{% endif %}><a href="{{ url_for(href|safe) }}">{{ caption|safe }}</a></li>
  {% endfor -%}
  </ul>
{% endblock %}

{% block banner %}
  <div class="container">
    <h1 class="sr-only">Banner</h1>
    <p class="lead text-center">アルファ版として公開中<br>順次、情報を追加していきます</p>
  </div>
{% endblock %}

{% block footer %}
  <div class="container">
    <ul class="footer-links text-muted">
      <li><a href="{{ url_for('setori.index') }}">ホーム</a></li>
      <li>·</li>
      <li><a href="{{ url_for('setori.about') }}">このサイトについて</a></li>
      <li>·</li>
      <li><a href="{{ url_for('setori.contact') }}">お問い合わせ</a></li>
    </ul>
    <p class="text-muted">&copy; 2015 setori.jp <a href="https://twitter.com/imas_setori">@imas_setori</a></p>
  </div>
  <div id="spot-im-root"></div>
{% endblock %}

{% block css %}
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/typeahead.css') }}">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap-select.min.css') }}">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/ion.rangeSlider.css') }}">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/ion.rangeSlider.skinFlat.css') }}">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/common.css') }}">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/colors.css') }}">
{% endblock %}

{% block script %}
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/locales.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='js/jquery.mixitup.min.js') }}"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='js/typeahead.bundle.min.js') }}"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap-select.min.js') }}"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='js/ion.rangeSlider.min.js') }}"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='js/jquery.japanese-input-change.min.js') }}"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='js/common.js') }}"></script>
  {% if page_id not in ['homepage', 'list', 'errorpage'] %}
  <script type="text/javascript">
      /* * * CONFIGURATION VARIABLES * * */
      var disqus_shortname = 'imas-setori';

      /* * * DON'T EDIT BELOW THIS LINE * * */
      (function() {
          var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
          dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
          (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
      })();
  </script>
  {% endif %}
  <script type="text/javascript">!function(t,o,p){function e(){var t=o.createElement("script");t.type="text/javascript",t.async=!0,t.src=("https:"==o.location.protocol?"https":"http")+":"+p,o.body.appendChild(t)}t.spotId="f2aeefdf4e95c404675620e1c31c8713",t.spotName="",t.allowDesktop=!0,t.allowMobile=!1,t.containerId="spot-im-root",e()}(window.SPOTIM={},document,"//www.spot.im/embed/scripts/launcher.js");</script>
  <script>(function(t,a,y,o,r,i){r=a.createElement(y),i=a.getElementsByTagName(y)[0];r.type='text/javascript';r.async=1;r.src='//tayori.com/form/b67117aeba020deb37e7722bec3b81be3aed04ad/tag.js';r.id='tayori-tag';i.parentNode.insertBefore(r,i)})(window,document,'script');</script>
{% endblock %}
