app/setori/__init__.py
# -*- coding: utf-8 -*-

# ┌─┐┌─┐┌┬┐┌─┐┬─┐┬
# └─┐├┤    │  │  │├┬┘│
# └─┘└─┘  ┴  └─┘┴└─┴

"""
Setori management library
~~~~~~~~~~~~~~~~~~~~~~~~~

Setori is a library that manages a content which have songs,
actors, characters, events and releases.

"""

from app import engine
from .exceptions import TableNotFound
import pandas as pd

__title__ = 'setori'
__version__ = '0.0.1'
__author__ = 'hironow'
__license__ = ''
__copyright__ = 'Copyright 2015 hironow'

tables = ['char', 'actr', 'char2actr', 'song',
          'event', 'song2actr2event', 'slsrc',
          'release', 'song2char2release', 'tlsrc']
for table in tables:
    if not engine.has_table(table):
        raise TableNotFound('Table %s not found' % table)

# Get database as pandas.DataFrame
df_char = pd.read_sql_table('char', engine)
df_actr = pd.read_sql_table('actr', engine)
df_char2actr = pd.read_sql_table('char2actr', engine)

df_song = pd.read_sql_table('song', engine)

df_event = pd.read_sql_table('event', engine)
df_song2actr2event = pd.read_sql_table('song2actr2event', engine)
df_slsrc = pd.read_sql_table('slsrc', engine)

df_release = pd.read_sql_table('release', engine)
df_song2char2release = pd.read_sql_table('song2char2release', engine)
df_tlsrc = pd.read_sql_table('tlsrc', engine)

# Convert datetime
df_char2actr['start_date'] = pd.to_datetime(df_char2actr['start_date'])
df_event['date'] = pd.to_datetime(df_event['date'])
df_release['date'] = pd.to_datetime(df_release['date'])

# Drop not using columns
if 'level_0' in df_song2actr2event.columns:
    df_song2actr2event.drop('level_0', axis=1, inplace=True)
if 'level_0' in df_song2char2release.columns:
    df_song2char2release.drop('level_0', axis=1, inplace=True)

app/setori/controllers.py
# -*- coding: utf-8 -*-

"""
setori.controllers
~~~~~~~~~~~~~~~~~~

This module contains the set of setori's controllers.

"""

from flask import (Blueprint, request, render_template,
                   redirect, url_for, abort)
from app import cache
from . import (df_song,
               df_actr,
               df_char,
               df_event,
               df_release,
               df_song2actr2event,
               df_song2char2release)
from .models import (search_models,
                     get_model,
                     get_models,
                     Song,
                     Actor,
                     Character,
                     Event,
                     Release,
                     SetList,
                     TrackList)
from .exceptions import (InvalidSongModel,
                         InvalidActorModel,
                         InvalidCharacterModel,
                         InvalidEventModel,
                         InvalidReleaseModel)
from urllib.parse import urlencode
from pandas.tslib import NaT
from collections import OrderedDict
from datetime import date


setori = Blueprint('setori', __name__, url_prefix='/')


def get_sorted_setlists(df_s2a2e):
    """セットリストのDataFrameからソート済みのセットリストModelのリストを取得する。
    """
    setlists = get_models(df_s2a2e, SetList,
                          ['event', 'part_number', 'order'], sort=False)
    setlists = sorted(setlists, key=lambda x: x.order, reverse=False)
    setlists = sorted(setlists, key=lambda x: x.part_number, reverse=False)
    setlists = sorted(setlists, key=lambda x: x.event.name, reverse=False)
    setlists = sorted(setlists, key=lambda x: x.event.date, reverse=True)

    return setlists


def get_sorted_tracklists(df_s2c2r):
    """トラックリストのDataFrameからソート済みのトラックリストModelのリストを取得する。
    """
    tracklists = get_models(df_s2c2r, TrackList,
                            ['release', 'disc_number', 'order'], sort=False)
    tracklists = sorted(tracklists, key=lambda x: x.order, reverse=False)
    tracklists = sorted(tracklists, key=lambda x: x.disc_number, reverse=False)
    tracklists = sorted(tracklists, key=lambda x: x.release.name, reverse=True)
    tracklists = sorted(tracklists, key=lambda x: x.release.date, reverse=True)

    return tracklists


def get_songs_actors_characters_via_setlists_tracklists(setlists, tracklists,
                                                        sort_by='name_kana'):
    """セットリストとトラックリスト、それぞれのリストから、そのすべての曲・役者・キャラクターのリストを取得する。

    :param setlists: セットリスト
    :type setlists: list
    :param tracklists: トラックリスト
    :type tracklists: list
    :param sort_by: sortを行なうcolumn名
    :type sort_by: str
    """

    # セットリストとトラックリスト、それぞれの役者とキャラクターを取得する
    grouped_actors_dicts = [l.set_actors() for l in setlists]
    grouped_characters_dicts = [l.set_characters() for l in tracklists]

    # セットリストとトラックリストの曲名を取得する
    song_names = [l.song.name for l in setlists]
    song_names += [l.song.name for l in tracklists]

    # セットリストとトラックリストの役者名を取得する
    actor_names = [actor.name for grouped_actors_dict in grouped_actors_dicts
                   for actors in grouped_actors_dict.values()
                   for actor in actors]
    actor_names += [actor.name
                    for grouped_characters_dict in grouped_characters_dicts
                    for characters in grouped_characters_dict.values()
                    for character in characters
                    for actor in character.actors]

    # セットリストとトラックリストのキャラクター名を取得する
    character_names = [character.name
                       for grouped_characters_dict in grouped_characters_dicts
                       for characters in grouped_characters_dict.values()
                       for character in characters]
    character_names += [character.name
                        for grouped_actors_dict in grouped_actors_dicts
                        for actors in grouped_actors_dict.values()
                        for actor in actors
                        for character in actor.characters]

    # 曲・役者・キャラクター名のリストをModel化する
    songs = get_models(
        df_song[df_song[Song._primary_key].isin(song_names)],
        Song, ['name'], sort=True, sort_by=sort_by)
    actors = get_models(
        df_actr[df_actr[Actor._primary_key].isin(actor_names)],
        Actor, ['name'], sort=True, sort_by=sort_by)
    characters = get_models(
        df_char[df_char[Character._primary_key].isin(character_names)],
        Character, ['name'], sort=True, sort_by=sort_by)

    return songs, actors, characters


@setori.app_template_filter('split_space')
def split_space(s):
    return s.strip().split()


@setori.app_template_filter('flatten_list')
def flatten_list(list_of_lists):
    return [i for l in list_of_lists for i in l]


@setori.app_template_filter('drop_duplicates')
def drop_duplicates(li):
    return list(OrderedDict.fromkeys(li))


@setori.app_template_filter('datetime')
def datetimeformat(value, format='%Y.%m.%d'):
    if value is NaT:
        return ''
    else:
        return str(value.strftime(format)).replace('.0', '.')


@setori.app_template_filter('lremove')
def lremoveformat(value, l):
    if value.startswith(l):
        return value[len(l):].strip()
    else:
        return value


def validate_queries(queries, permitted_query_keys):
    """
    :param queries: ImmutableMultiDict
    :param list permitted_query_keys: list
    """
    if set(queries) != set(permitted_query_keys):
        abort(400)  # catch not corrected query key
    elif any(len(queries.getlist(key)) != 1 for key in permitted_query_keys):
        abort(400)  # catch duplicated query key


@setori.route('', methods=['GET'])
def index():
    song_length = len(df_song[df_song['type'] == ''])
    actor_length = len(df_actr)
    character_length = len(df_char)
    event_length = len(df_event[df_event['part_number'] == 1])
    release_length = len(df_release[df_release['disc_number'] == 1])

    df_e = df_event[df_event['date'] <= date.today()]
    df_r = df_release[df_release['date'] <= date.today()]

    events = get_models(df_e.drop_duplicates('name').sort(
                        ['date', 'name'], ascending=[False, False]).head(3),
                        Event, ['name'], sort=False)
    releases = get_models(df_r.drop_duplicates('name').sort(
                        ['date', 'name'], ascending=[False, False]).head(3),
                        Release, ['name'], sort=False)

    return render_template('setori/index.html',
                           song_length=song_length,
                           actor_length=actor_length,
                           character_length=character_length,
                           event_length=event_length,
                           release_length=release_length,
                           events=events,
                           releases=releases)


@setori.route('about', methods=['GET'])
def about():
    return render_template('setori/about.html')


@setori.route('contact', methods=['GET'])
def contact():
    return render_template('setori/contact.html')


@setori.route('search', methods=['GET'])
def search():
    validate_queries(request.args, ['o', 'q'])

    # not immutable dict for redirecting after
    request_args = request.args.to_dict()
    obj = request_args.pop('o')

    if obj == 'song':
        return redirect(url_for('.songs') + '?' + urlencode(request_args))
    elif obj == 'actor':
        return redirect(url_for('.actors') + '?' + urlencode(request_args))
    elif obj == 'character':
        return redirect(url_for('.characters') + '?' + urlencode(request_args))
    else:
        abort(400)
    return render_template('setori/index.html')


@setori.route('songs', methods=['GET'])
def songs():
    if request.args.get('q'):
        validate_queries(request.args, ['q'])
        searchword = request.args['q']

        songs = search_models(searchword, df_song, Song)
        if len(songs) == 0:
            abort(404)
        elif len(songs) == 1:
            return redirect(url_for('.song', name=songs[0].name))
        else:
            return render_template('setori/results.html', o='song',
                                   q=searchword,
                                   songs=songs)

    songs = get_models(df_song, Song, ['name'], sort_by='name_kana')
    return render_template('setori/songs.html', songs=songs)


@setori.route('songs/<name>', methods=['GET'])
@cache.cached(timeout=2592000)
def song(name):
    df_s = df_song[df_song['name'] == name]
    df_s2a2e = df_song2actr2event[df_song2actr2event['song'] == name]
    df_s2c2r = df_song2char2release[df_song2char2release['song'] == name]

    try:
        song = get_model(df_s, Song, ['name'])
    except (ValueError, InvalidSongModel):
        abort(404)
    setlists = get_sorted_setlists(df_s2a2e)
    tracklists = get_sorted_tracklists(df_s2c2r)
    (_, actors,
        characters) = get_songs_actors_characters_via_setlists_tracklists(
        setlists, tracklists, sort_by='name_kana')

    return render_template('setori/song.html', song=song,
                           setlists=setlists, tracklists=tracklists,
                           actors=actors, characters=characters)


@setori.route('actors', methods=['GET'])
def actors():
    if request.args.get('q'):
        validate_queries(request.args, ['q'])
        searchword = request.args['q']

        actors = search_models(searchword, df_actr, Actor)
        if len(actors) == 0:
            abort(404)
        elif len(actors) == 1:
            return redirect(url_for('.actor', name=actors[0].name))
        else:
            return render_template('setori/results.html', o='actor',
                                   q=searchword,
                                   actors=actors)

    actors = get_models(df_actr, Actor, ['name'],
                        sort_by='name_kana')
    [actor.set_characters([]) for actor in actors]
    return render_template('setori/actors.html', actors=actors)


@setori.route('actors/<name>', methods=['GET'])

app/templates/setori/snippet/forms.html
{#
  templates/setori/snippet/forms.html
#}
{% set objs = {'song': '曲', 'actor': '役者', 'character': 'キャラクター'} %}

{% macro search_form(obj='song', q='', size='md') %}
  <form class="search-form" action="{{ url_for('setori.search') }}" method="get">
    {% if size == 'lg' %}
    <div class="input-group input-group-lg">
    {% else %}
    <div class="input-group">
    {% endif %}
      <div class="input-group-btn input-group-select">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          <span class="concept">{{ objs[obj] }}</span> <i class="fa fa-caret-down"></i></button>
        <ul class="dropdown-menu" role="menu">
          <li><a href="#song">曲</a></li>
          <li><a href="#actor">役者</a></li>
          <li><a href="#character">キャラクター</a></li>
          <!-- <li><a href="#creator">クリエイター</a></li> -->
        </ul>
        <input type="hidden" name="o" value="{{ obj }}" class="input-group-select-val">
      </div><!-- /btn-group -->
      <input type="text" name="q" class="form-control typeahead song" value="{{ q|e }}">
      <span class="input-group-btn">
        <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
      </span>
    </div><!-- /input-group -->
  </form>
{% endmacro %}

app/templates/setori/snippet/lists.html
{#
  templates/setori/snippet/lists.html
#}

{% macro get_classes(lists, attribute) %}
  {{- lists|map(attribute=attribute)|map('replace', ' ', '-')|join(' ') -}}
{% endmacro %}

{% macro get_index_classes(lists, prefix) %}
  {%- for list in lists -%}
    {% if not loop.first %} {% endif %}
    {{- prefix -}}-{{- list.index -}}
  {%- endfor -%}
{% endmacro %}

{% macro get_select_filter(songs, actors, characters) %}
  <select class="selectpicker show-tick" id="filter-select" data-live-search="true">
    <option value="all" selected>すべて</option>

    {% if songs %}
    {% for song in songs %}
    {% if loop.first %}
    <optgroup label="曲">
    {% endif %}
      <option value=".s-{{- song.index -}}">{{ song.name }}</option>
    {% if loop.last %}
    </optgroup>
    {% endif %}
    {% endfor %}
    {% endif %}

    {% for actor in actors %}
    {% if loop.first %}
    <optgroup label="役者">
    {% endif %}
      <option value=".a-{{- actor.index -}}">{{ actor.name }}</option>
    {% if loop.last %}
    </optgroup>
    {% endif %}
    {% endfor %}

    {% for character in characters %}
    {% if loop.first %}
    <optgroup label="キャラクター">
    {% endif %}
      <option value=".c-{{- character.index -}}">{% if character.alias %}{{ character.alias }}{% else %}{{ character.name }}{% endif %}</option>
    {% if loop.last %}
    </optgroup>
    {% endif %}
    {% endfor %}
  </select>
{% endmacro %}

{% macro get_actor_buttons(actors) %}
  {% for actor in actors %}
  <a href="{{ url_for('setori.actor', name=actor.name) }}" role="button" class="btn btn-xs btn-labeled filtered {{ get_index_classes([actor], prefix='a') }} {{ get_index_classes(actor.characters, prefix='c') }} {{ actor.characters|map(attribute='name_alphabet')|map('replace', ' ', '-')|join(' ')}}"><span class="btn-label-left">{{ actor.name.replace(' ', '') }}</span>{% for character in actor.characters %}{% if not loop.first %} · {% endif %}{% if character.alias %}{{ character.alias.replace(' ', '') }}{% else %}{{ character.name.replace(' ', '') }}{% endif %}{% endfor %}役</a>
  {% endfor %}
{% endmacro %}

{% macro get_actor_filtered_buttons(actors) %}
  {% for actor in actors %}
  <a href="{{ url_for('setori.actor', name=actor.name) }}" role="button" class="btn btn-sm mix btn-labeled filtered {{ get_index_classes([actor], prefix='a') }} {{ get_index_classes(actor.characters, prefix='c') }} {{ actor.characters|map(attribute='name_alphabet')|map('replace', ' ', '-')|join(' ')}}"><span class="btn-label-left">{{ actor.name.replace(' ', '') }}</span>{% for character in actor.characters %}{% if not loop.first %} · {% endif %}{% if character.alias %}{{ character.alias.replace(' ', '') }}{% else %}{{ character.name.replace(' ', '') }}{% endif %}{% endfor %}役<p class="sr-only">{{ actor.name_kana }}{{ actor.name_alphabet }}</p></a>
  {% endfor %}
{% endmacro %}

{% macro get_character_buttons(characters) %}
  {% for character in characters %}
  <a href="{{ url_for('setori.character', name=character.name) }}" role="button" class="btn btn-xs btn-labeled filtered {{ get_index_classes([character], prefix='c') }} {{ get_index_classes(character.actors, prefix='a') }} {{ character.name_alphabet.replace(' ', '-') }}">{% if character.alias %}{{ character.alias.replace(' ', '') }}{% else %}{{ character.name.replace(' ', '') }}{% endif %}<span class="btn-label-right">CV.{{ character.actors|map(attribute='name')|map('replace', ' ', '')|join(' · ')}}</span></a>
  {% endfor %}
{% endmacro %}

{% macro get_character_filtered_buttons(characters) %}
  {% for character in characters %}
  <a href="{{ url_for('setori.character', name=character.name) }}" role="button" class="btn btn-sm mix{% if character.actors %} btn-labeled{% endif %} filtered {{ get_index_classes([character], prefix='c') }} {{ get_index_classes(character.actors, prefix='a') }} {{ character.name_alphabet.replace(' ', '-') }}">{% if character.alias %}{{ character.alias.replace(' ', '') }}{% else %}{{ character.name.replace(' ', '') }}{% endif %}{% if character.actors %}<span class="btn-label-right">CV.{{ character.actors|map(attribute='name')|map('replace', ' ', '')|join(' · ')}}</span>{% endif %}<p class="sr-only">{{ character.name_kana }}{{ character.name_alphabet }}</p></a>
  {% endfor %}
{% endmacro %}

{% macro get_setlist_date_column(setlist, song=True) %}
  <strong>{{ setlist.event.date|datetime }}</strong>

  {% if setlist.song.song_version %}
  <span class="label label-primary">{{ setlist.song.song_version }}</span>
  {% endif %}
  {% if setlist.song.type %}
  <span class="label label-success">{{ setlist.song.type }}</span>
  {% endif %}

  <div class="media">
  {% if setlist.event.parts[setlist.part_number - 1].amazon_medium_image_link %}
    <div class="media-left">
      <a href="{{ url_for('setori.event', name=setlist.event.name) }}"><img class="media-object" src="{{ setlist.event.parts[setlist.part_number - 1].amazon_medium_image_link }}" alt="{{ setlist.event.name }}"></a>
    </div>
  {% endif %}
    <div class="media-body">
    <h3 class="media-heading">
      <a href="{{ url_for('setori.event', name=setlist.event.name) }}"><strong>{{ setlist.event.name }}</strong></a> @{{ setlist.event.venue }}

      {% if setlist.part_name %}
      <span class="label label-default">{{ setlist.part_name }}</span>
      {% endif %}
    </h3>

    <a href="{{ url_for('setori.event', name=setlist.event.name) }}" role="button" class="btn btn-xs order{% if setlist.type %} btn-labeled{% endif %}">{{ setlist.order }}{% if setlist.type %}<span class="btn-label-right">{{ setlist.type }}</span>{% endif %}</a>
    {% if song %}
    <a href="{{ url_for('setori.song', name=setlist.song.name) }}" role="button" class="btn btn-link"><strong>{{ setlist.song.name }}</strong></a>
    {% endif %}

    </div>
  </div>
{% endmacro %}

{% macro get_setlist_order_column(setlist) %}
  <a href="{{ url_for('setori.event', name=setlist.event.name) }}" role="button" class="btn btn-sm order{% if setlist.type %} btn-labeled{% endif %}">{{ setlist.order }}{% if setlist.type %}<span class="btn-label-right">{{ setlist.type }}</span>{% endif %}</a>
  <a href="{{ url_for('setori.song', name=setlist.song.name) }}" role="button" class="btn btn-link"><strong>{{ setlist.song.name }}</strong></a>

  {% if setlist.song.song_version %}
  <span class="label label-primary">{{ setlist.song.song_version }}</span>
  {% endif %}

  {% if setlist.song.type %}
  <span class="label label-success">{{ setlist.song.type }}</span>
  {% endif %}
{% endmacro %}

{% macro get_tracklist_date_column(tracklist, song=True) %}
  <strong>{{ tracklist.release.date|datetime }}</strong>

  {% if tracklist.song.song_version %}
  <span class="label label-primary">{{ tracklist.song.song_version }}</span>
  {% endif %}

  {% if tracklist.song.type %}
  <span class="label label-success">{{ tracklist.song.type }}</span>
  {% endif %}

  <div class="media">
  {% if tracklist.release.discs[tracklist.disc_number - 1].amazon_medium_image_link %}
    <div class="media-left">
      <a href="{{ url_for('setori.release', name=tracklist.release.name) }}"><img class="media-object" src="{{ tracklist.release.discs[tracklist.disc_number - 1].amazon_medium_image_link }}" alt="{{ tracklist.release.name }}"></a>
    </div>
  {% endif %}
    <div class="media-body">
      <h3 class="media-heading">
        <a href="{{ url_for('setori.release', name=tracklist.release.name) }}"><strong>{{ tracklist.release.name }}</strong></a>

      {% if tracklist.disc_name %}
      <span class="label label-default">{{ tracklist.disc_name }}</span>
      {% endif %}
      </h3>

      <a href="{{ url_for('setori.release', name=tracklist.release.name) }}" role="button" class="btn btn-xs order{% if tracklist.type %} btn-labeled{% endif %}">{{ tracklist.order }}{% if tracklist.type %}<span class="btn-label-right">{{ tracklist.type }}</span>{% endif %}</a>
      {% if song %}
      <a href="{{ url_for('setori.song', name=tracklist.song.name) }}" role="button" class="btn btn-link"><strong>{{ tracklist.song.name }}</strong></a>
      {% endif %}

    </div>
  </div>
{% endmacro %}

{% macro get_tracklist_order_column(tracklist) %}
  <a href="{{ url_for('setori.release', name=tracklist.release.name) }}" role="button" class="btn btn-sm order{% if tracklist.type %} btn-labeled{% endif %}">{{ tracklist.order }}{% if tracklist.type %}<span class="btn-label-right">{{ tracklist.type }}</span>{% endif %}</a>

  <a href="{{ url_for('setori.song', name=tracklist.song.name) }}" role="button" class="btn btn-link"><strong>{{ tracklist.song.name }}</strong></a>

  {% if tracklist.song.song_version %}
  <span class="label label-primary">{{ tracklist.song.song_version }}</span>
  {% endif %}

  {% if tracklist.song.type %}
  <span class="label label-success">{{ tracklist.song.type }}</span>
  {% endif %}
{% endmacro %}